// <auto-generated />
using System;
using HandsOnEFCore_CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HandsOnEFCore_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20191112103815_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HandsOnEFCore_CodeFirst.Models.Dept", b =>
                {
                    b.Property<string>("Did")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Did");

                    b.ToTable("Dept");
                });

            modelBuilder.Entity("HandsOnEFCore_CodeFirst.Models.Employee", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desig")
                        .HasColumnName("Designation")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Did")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sal")
                        .HasColumnName("Salary")
                        .HasColumnType("int");

                    b.HasKey("Eid");

                    b.HasIndex("Did");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HandsOnEFCore_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnName("Std")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("School")
                        .HasColumnType("char(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.ToTable("Student1");
                });

            modelBuilder.Entity("HandsOnEFCore_CodeFirst.Models.Employee", b =>
                {
                    b.HasOne("HandsOnEFCore_CodeFirst.Models.Dept", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("Did");
                });
#pragma warning restore 612, 618
        }
    }
}
